name: Worflow basique

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      -main
      
env:
  MAVEN_OPTS: "-Dmaven.repo.local=/home/runner/work/lib"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.2.2
        
      - name: "Setup Java JDK"
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: 'zulu'
 
      - name: "Cache" 
        uses: actions/cache@v4.1.2
        with:
          path: "/home/runner/work/lib"
          key: ${{ runner.os }}-maven-${{ hashFiles('**pom.xml') }}
          
      - name: "Job de build"
        run: mvn clean package -DskipTests -Djar.finalName=${{github.repository}}-${{vars.PROJECT_VERSION}} 

      - name: "Upload d'artifact"
        uses: actions/upload-artifact@v4.4.3
        with:
          path: /home/runner/work/helloworld-java/helloworld-java/target/${{github.repository}}-${{vars.PROJECT_VERSION}}.jar
          if-no-files-found: warn

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
       - name: "Checkout"
         uses: actions/checkout@v4.2.2

       - name: "Setup Java JDK"
         uses: actions/setup-java@v4.5.0
         with:
          java-version: 17
          distribution: 'zulu'

       - name: "Cache" 
         uses: actions/cache@v4.1.2
         with:
           path: "/home/runner/work/lib"
           key: ${{ runner.os }}-maven-${{ hashFiles('**pom.xml') }}
    
       - name: "Lancement des tests"
         run: mvn test
    
