name: Worflow basique

on: 
  push:
    branches:
      - main

jobs:
  main_job:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Java JDK"
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: zulu
      - name: "Job de build"
        run: mvn clean package -DskipTests -Djar.finalName=${{github.repository}}-${{vars.PROJECT_VERSION}}
